# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o bin/lgl-matrix-maker -buildvcs=false -v ./...

    - name: Test
      run: go test -v ./...

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: bin/lgl-matrix-maker
